### PR TITLE
got this working again

### PR DESCRIPTION
**Pull request by ghost**
Hi,

I managed to get your bindings working on ccl under linux - this is totally awesome!  Maybe I'll find time to wrap the bare bindings in some helper functions so it offers a restart to recompile & try again when code inside the realtime thread blows up...

### CODE REVIEW

**Comment by ichiban** [comment]
Hi, @rick-monster 

Thank you for reviving it! It's been 5 years since the last commit!
It contains linux specific code so it doesn't run on my macbook but your commits look awesome.
I'm going to merge it.

Also, I've come up with some improvements to make it platform-independent.
I'll dig into parentheses and play with Jack again.

**Comment by ghost** [comment]
hey I've got somewhat bogged down fiddling with lisp garbage collectors.  This guy has jack working well with sbcl as well but actually the same problems come up - maybe a little worse than in ccl!

http://incudine.sourceforge.net/

so there seem to be a fundamental problem that we don't have a metronome garbage collector for lisp like this one:

http://researcher.watson.ibm.com/researcher/files/us-bacon/Bacon03Metronome.pdf

so until someone really clever digs into ccl or sbcl to give some constraints to maximum stop-the-world time for the gc the right approach is to make sure all dsp code is non-consing.  Maybe it's possible to have already-runnning full gc in ccl or sbcl catch the signal to announce start of a jack frame and just stop!

Obviously if this happens often, the gc can't finish and memory leak will occur.  Meanwhile there is also the hack to reduce _average_ gc time by moving almost all of the program into non-data memory using #'save-application.  Using this technique, can get latency around 200ms with no xruns....

**Comment by ichiban** [comment]
Hi, @rick-monster

I don't catch up with this yet. I thought it would be mostly non-consing inside process callbacks (or any other speed focused code) or isn't it in practice?

I heard some folks in Ruby on Rails community actually stopped the GC while processing HTTP requests for performance. Perhaps we can do a same trick inside the callbacks with `CCL:WITHOUT-GCING`?

**Comment by ghost** [comment]
Hey so got a little further seeing what can be done without getting crazy and hacking on the lisp implementation.  Briefly I conclude that ccl is better in a situation where you want to write quick&dirty/experimental code conses a lot.  In this case I had some luck wrapping the whole callback in ccl:without-gcing, setting the limit for full garbage collection very high and some particular values for the egc limits.

This allows me to get the 200ms latency with no xruns barring full gc.  Full gc can still drop audio frames (once an hour or so running deliberately dirty code) - I believe this probably occurs when gc is in progress when the callback is scheduled to start.  So I would prefer to find a way to _always_ trigger full gc at end of each audio frame, just after the callback returns.  However this very occasional xrun is now ok for my purposes.  Also I made xrun trigger lisp debugger in a manageable way so at least it's obvious when that happens.

Because ccl compiler doesn't cons much this combination of cl-jack and ccl is the best for typical slime/emacs interactive workflow while audio runs through the program.

In the situation where you require minimal latency and you can afford to write optimised code (for example a software synthesizer), incudine is king - non-consing code can be compiled down to something with c-like realtime performance - think I was getting <5ms.  However sbcl conses a lot when compiling and I found it impossible to use typical slime/emacs flow with incudine/sbcl environment without dropping audio frames - even at very conservative latency...

**Pull request merged**
